import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/custom-components/header";
import { Toaster } from "@/components/ui/toaster";
import Providers from "./providers";
import Footer from "../components/custom-components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <Toaster />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
